# Generated by Django 3.2.18 on 2023-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcoursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('studentid', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255)),
                ('maincourse', models.CharField(max_length=255)),
                ('alternatecourse', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('date', models.DateField()),
            ],
        ),
    ]
